function(print_banner)
    message(STATUS "${BoldMagenta}   ____                        _       ${ColorReset}")
    message(STATUS "${BoldMagenta}  / ___|  ___ __ _ _ __  _   _| | __ _ ${ColorReset}")
    message(STATUS "${BoldMagenta}  \\___ \\ / __/ _` | '_ \\| | | | |/ _` |${ColorReset}")
    message(STATUS "${BoldMagenta}   ___) | (_| (_| | |_) | |_| | | (_| |${ColorReset}")
    message(STATUS "${BoldMagenta}  |____/ \\___\\__,_| .__/ \\__,_|_|\\__,_|${ColorReset}")
    message(STATUS "${BoldMagenta}                  |_|                  ${ColorReset}")
    message(STATUS "")
endfunction(print_banner)
