import io

from dataclasses import dataclass
from shoulder.gadget.gadget_properties import GadgetProperties

@dataclass
class properties(GadgetProperties):
    """ Properties of the testcase gadget """

    gadget_name: str = "scapula.gadget.testcase"
    """ Name of the gadget these properties apply to """

    count: int = 0
    """ The number of testcases generated by this gadget """

    prefix: str = "test_case"
    """ A string prefix for the generated function name """

    verbose: bool = False
    """ Set to True to generate verbose print statements """

    indent_contents: bool = True
    """ Set True to indent testcase contents one level above definition """

def testcase(decorated):
    """
    A decorator gadget that generates a function to wrap a single test case.
    The functions generated by this gadget have names of the form
    <prefix>_<counter>, where prefix is a decorator argument, and counter is
    incremented by one for each function generated by this gadget.

    Usage:
        @testcase
        function(generator, outfile, ...):
            outfile.write("inside the test case")

    Generates:
        void test_case_0(void)
        {
            inside the test case
        }
    """

    def testcase_decorator(generator, outfile, *args, **kwargs):

        properties = generator.gadgets["scapula.gadget.testcase"]

        testcase_name = properties.prefix + "_" + str(properties.count)
        testcase_call = "void " + testcase_name + "(void)\n"

        outfile.write(testcase_call)
        outfile.write("{\n")

        contents = io.StringIO()

        if properties.verbose == True:
            banner_text = "**********************************************"
            contents.write("SCAPULA_PRINT(\"" + banner_text + "\");\n")

            testcase_text = "Running: " + testcase_name
            contents.write("SCAPULA_PRINT(\"" + testcase_text + "\");\n")

        decorated(generator, contents, *args, **kwargs)

        if properties.verbose == True:
            contents.write("SCAPULA_PRINT(\"... test complete\");\n")

        lines = contents.getvalue().splitlines()

        if len(lines) == 1:
            outfile.write(" ")
            outfile.write(lines[0])
            outfile.write(" ")

        elif len(lines) > 1:
            for line in lines:
                if properties.indent_contents:
                    outfile.write("\t")
                outfile.write(line + "\n")

        outfile.write("}\n\n")

        properties.count = properties.count + 1

    return testcase_decorator
